from enum import Enum


class Direction(Enum):
    LEFT = 0
    RIGHT = 1
    UP = 2
    DOWN = 3

class Orientation(Enum):
    HORIZONTAL = 0
    VERTICAL = 1

class GameMode(Enum):
    HOME_SCREEN = 0
    SINGLE_PLAY = 1
    MULTI_PLAY = 2
    PAUSE = 3
    WIN = 4
    GAME_OVER = 5
    MULTI_END = 6
    CLOSE_WINDOW = 7

class SupportedFruit(Enum):
    STRAWBERRY = 0
    CHERRY = 1
    ORANGE = 2

BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
DARK_BLUE = (0, 0, 139)
LIGHT_PINK = (255, 204, 229)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)
LIGHT_GRAY = (170, 170, 170)
DARK_GRAY = (100, 100, 100)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Default settings
CHARACTER_SPEED = 0.2
THIN_WALL_THICKNESS = 10
MEDIUM_WALL_THICKNESS = 2 * THIN_WALL_THICKNESS
THICK_WALL_THICKNESS = 4 * THIN_WALL_THICKNESS
LANE_SIZE = 4 * THIN_WALL_THICKNESS

# Board Settings
# screen height = 10 lanes + 4 thin walls + 6 medium walls + 1 thick wall, + 4 outside lanes
SCREEN_HEIGHT = 10*LANE_SIZE + 4*THIN_WALL_THICKNESS + 6*MEDIUM_WALL_THICKNESS + 1*THICK_WALL_THICKNESS + 4*LANE_SIZE
# screen width = 10 lanes + 2 thin walls + 7 medium walls, + 2 outside lanes
SCREEN_WIDTH = 10*LANE_SIZE + 2*THIN_WALL_THICKNESS + 7*MEDIUM_WALL_THICKNESS + 2*LANE_SIZE

# Lanes
# Vertical Lanes
LANE_VERTICAL_1_LONGITUDE = LANE_SIZE + THIN_WALL_THICKNESS + LANE_SIZE/2
LANE_VERTICAL_2_LONGITUDE = LANE_VERTICAL_1_LONGITUDE + LANE_SIZE
LANE_VERTICAL_3_LONGITUDE = LANE_VERTICAL_2_LONGITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_VERTICAL_4_LONGITUDE = LANE_VERTICAL_3_LONGITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_VERTICAL_5_LONGITUDE = LANE_VERTICAL_4_LONGITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_VERTICAL_5_5_LONGITUDE = SCREEN_WIDTH/2
LANE_VERTICAL_6_LONGITUDE = SCREEN_WIDTH - LANE_VERTICAL_5_LONGITUDE
LANE_VERTICAL_7_LONGITUDE = SCREEN_WIDTH - LANE_VERTICAL_4_LONGITUDE
LANE_VERTICAL_8_LONGITUDE = SCREEN_WIDTH - LANE_VERTICAL_3_LONGITUDE
LANE_VERTICAL_9_LONGITUDE = SCREEN_WIDTH - LANE_VERTICAL_2_LONGITUDE
LANE_VERTICAL_10_LONGITUDE = SCREEN_WIDTH - LANE_VERTICAL_1_LONGITUDE
# Horizontal Lanes
LANE_HORIZONTAL_1_LATTITUDE = 2*LANE_SIZE + THIN_WALL_THICKNESS + LANE_SIZE/2
LANE_HORIZONTAL_2_LATTITUDE = LANE_HORIZONTAL_1_LATTITUDE + LANE_SIZE*2
LANE_HORIZONTAL_3_LATTITUDE = LANE_HORIZONTAL_2_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_4_LATTITUDE = LANE_HORIZONTAL_3_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_5_LATTITUDE = LANE_HORIZONTAL_4_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_6_LATTITUDE = LANE_HORIZONTAL_5_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_7_LATTITUDE = LANE_HORIZONTAL_6_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_8_LATTITUDE = LANE_HORIZONTAL_7_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_9_LATTITUDE = LANE_HORIZONTAL_8_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS
LANE_HORIZONTAL_10_LATTITUDE = LANE_HORIZONTAL_9_LATTITUDE + LANE_SIZE + MEDIUM_WALL_THICKNESS

# Horizontal, lattitudal walls
# Upper Walls
WALL_LATITUDE_1 = 2 * LANE_SIZE
WALL_LATITUDE_2 = WALL_LATITUDE_1 + THIN_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_3 = WALL_LATITUDE_2 + THICK_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_4 = WALL_LATITUDE_3 + MEDIUM_WALL_THICKNESS + LANE_SIZE
# Middle Walls
WALL_LATITUDE_5_OUTSIDE = WALL_LATITUDE_4 + MEDIUM_WALL_THICKNESS + LANE_SIZE + THIN_WALL_THICKNESS
WALL_LATITUDE_5_INSIDE = WALL_LATITUDE_4 + MEDIUM_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_6_OUTSIDE = WALL_LATITUDE_5_OUTSIDE + THIN_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_6_INSIDE = WALL_LATITUDE_6_OUTSIDE + THIN_WALL_THICKNESS
# Lower Walls
WALL_LATITUDE_7_INSIDE = WALL_LATITUDE_6_INSIDE + THIN_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_7_OUTSIDE = WALL_LATITUDE_7_INSIDE + THIN_WALL_THICKNESS
WALL_LATITUDE_8 = WALL_LATITUDE_7_OUTSIDE + THIN_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_9 = WALL_LATITUDE_8 + MEDIUM_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_10 = WALL_LATITUDE_9 + MEDIUM_WALL_THICKNESS + LANE_SIZE
WALL_LATITUDE_11 = WALL_LATITUDE_10 + MEDIUM_WALL_THICKNESS + LANE_SIZE

# Vertical, longitudal walls
# Leftern Walls
WALL_LONGITUDE_1 = 1 * LANE_SIZE
WALL_LONGITUDE_2_OUTER = WALL_LONGITUDE_1 + THIN_WALL_THICKNESS + 2*LANE_SIZE
WALL_LONGITUDE_2_INNER = WALL_LONGITUDE_2_OUTER + THIN_WALL_THICKNESS
WALL_LONGITUDE_3 = WALL_LONGITUDE_2_OUTER + MEDIUM_WALL_THICKNESS + LANE_SIZE
WALL_LONGITUDE_4 = WALL_LONGITUDE_3 + MEDIUM_WALL_THICKNESS + LANE_SIZE
# Middle Wall
WALL_LONGITUDE_5 = WALL_LONGITUDE_4 + MEDIUM_WALL_THICKNESS + LANE_SIZE
# Rightern Walls
WALL_LONGITUDE_6 = WALL_LONGITUDE_5 + MEDIUM_WALL_THICKNESS + LANE_SIZE + THIN_WALL_THICKNESS
WALL_LONGITUDE_7 = WALL_LONGITUDE_6 + THIN_WALL_THICKNESS + LANE_SIZE
WALL_LONGITUDE_8 = WALL_LONGITUDE_7 + MEDIUM_WALL_THICKNESS + LANE_SIZE
WALL_LONGITUDE_9 = WALL_LONGITUDE_8 + MEDIUM_WALL_THICKNESS + 2*LANE_SIZE


# All Wall Lengths
# 7 Horizontal wall lengths
WALL_HORIZONTAL_LENGTH_1 = WALL_LONGITUDE_9 - WALL_LONGITUDE_1 + THIN_WALL_THICKNESS
WALL_HORIZONTAL_LENGTH_2 = (WALL_LONGITUDE_2_INNER + THIN_WALL_THICKNESS) - (WALL_LONGITUDE_1 + THIN_WALL_THICKNESS + LANE_SIZE)
WALL_HORIZONTAL_LENGTH_3 = (WALL_LONGITUDE_5-LANE_SIZE) - WALL_LONGITUDE_3 
WALL_HORIZONTAL_LENGTH_4 = (WALL_LONGITUDE_6 + THIN_WALL_THICKNESS) - WALL_LONGITUDE_4
WALL_HORIZONTAL_LENGTH_5 = (WALL_LONGITUDE_2_INNER + THIN_WALL_THICKNESS) - WALL_LONGITUDE_1
WALL_HORIZONTAL_LENGTH_6 = LANE_SIZE + THIN_WALL_THICKNESS
WALL_HORIZONTAL_LENGTH_7 = WALL_LONGITUDE_5 - WALL_LONGITUDE_1 - THIN_WALL_THICKNESS - 2*LANE_SIZE
# Vertical wall lengths
WALL_VERTICAL_LENGTH_1 = WALL_LATITUDE_4 + THIN_WALL_THICKNESS - WALL_LATITUDE_1
WALL_VERTICAL_LENGTH_2 = WALL_LATITUDE_11 + THIN_WALL_THICKNESS - WALL_LATITUDE_7_OUTSIDE
WALL_VERTICAL_LENGTH_3 = WALL_LATITUDE_5_OUTSIDE + THIN_WALL_THICKNESS - WALL_LATITUDE_4
WALL_VERTICAL_LENGTH_4 = WALL_LATITUDE_9 + MEDIUM_WALL_THICKNESS - WALL_LATITUDE_8
