from enum import Enum


class Direction(Enum):
    LEFT = 0
    RIGHT = 1
    UP = 2
    DOWN = 3

class Orientation(Enum):
    HORIZONTAL = 0
    VERTICAL = 1

# Default settings
CHARACTER_SPEED = 0.2
THIN_WALL_THICKNESS = 10
MEDIUM_WALL_THICKNESS = 2 * THIN_WALL_THICKNESS
THICK_WALL_THICKNESS = 4 * THIN_WALL_THICKNESS
LANE_SIZE = 4 * THIN_WALL_THICKNESS
CHARACTER_SIZE = LANE_SIZE

# Colors
BLACK = (0,0,0)
BLUE = (0,0,255)

# Board Settings
# screen height = 10 lanes + 4 thin walls + 6 medium walls + 1 thick wall, + 4 outside lanes
SCREEN_HEIGHT = 10*LANE_SIZE + 4*THIN_WALL_THICKNESS + 6*MEDIUM_WALL_THICKNESS + 1*THICK_WALL_THICKNESS + 4*LANE_SIZE
# screen width = 10 lanes + 4 thin walls + 5 medium walls, + 2 outside lanes
SCREEN_WIDTH = 10*LANE_SIZE + 4*THIN_WALL_THICKNESS + 5*MEDIUM_WALL_THICKNESS + 2*LANE_SIZE

# Horizontal, lattitudal walls
# Upper Walls
WALL_LATITUDE_1 = 2 * CHARACTER_SIZE
WALL_LATITUDE_1_THICKNESS = THIN_WALL_THICKNESS
WALL_LATITUDE_2 = WALL_LATITUDE_1 + WALL_LATITUDE_1_THICKNESS + LANE_SIZE
WALL_LATITUDE_2_THICKNESS = THICK_WALL_THICKNESS
WALL_LATITUDE_3 = WALL_LATITUDE_2 + WALL_LATITUDE_2_THICKNESS + LANE_SIZE
WALL_LATITUDE_4 = WALL_LATITUDE_3 + WALL_LATITUDE_3_THICKNESS + LANE_SIZE
WALL_LATITUDE_4_OUTSIDE_THICKNESS = THIN_WALL_THICKNESS
WALL_LATITUDE_4_INSIDE_THICKNESS = MEDIUM_WALL_THICKNESS
# Middle Walls
WALL_LATITUDE_5_THICKNESS = THIN_WALL_THICKNESS
WALL_LATITUDE_5_OUTSIDE = WALL_LATITUDE_4 + WALL_LATITUDE_4_INSIDE_THICKNESS + LANE_SIZE + WALL_LATITUDE_5_THICKNESS
WALL_LATITUDE_5_INSIDE = WALL_LATITUDE_4 + WALL_LATITUDE_4_INSIDE_THICKNESS + LANE_SIZE
# TODO: To be continued

# Vertical, Longitudal walls
# Leftern Walls
FIRST_WALL_LONGITUDE = 1 * CHARACTER_SIZE
SECOND_WALL_LONGITUDE = FIRST_WALL_LONGITUDE + WALL_THICKNESS + 2*CHARACTER_SIZE
THIRD_WALL_LONGITUDE = SECOND_WALL_LONGITUDE + WALL_THICKNESS + CHARACTER_SIZE
FOURTH_WALL_LATTITUDE = THIRD_WALL_LONGITUDE + WALL_THICKNESS + CHARACTER_SIZE
# Middle Wall
FIFTH_WALL_LONGITUDE = FOURTH_WALL_LATTITUDE + WALL_THICKNESS + CHARACTER_SIZE
# Rightern Walls
SIXTH_WALL_LONGITUDE = FIFTH_WALL_LONGITUDE + WALL_THICKNESS + CHARACTER_SIZE
SEVENTH_WALL_LONGITUDE = SIXTH_WALL_LONGITUDE + WALL_THICKNESS + CHARACTER_SIZE
EIGTH_WALL_LONGITUDE = SEVENTH_WALL_LONGITUDE + WALL_THICKNESS + CHARACTER_SIZE
NINTH_WALL_LONGITUDE = EIGTH_WALL_LONGITUDE + WALL_THICKNESS + 2*CHARACTER_SIZE