import pygame
from constants import *
import public_vars
from objects import Wall

def create_map():
    walls = []
    # Wall(x, y, orientation, thickness, length)
    # Horizontal Walls
    # WALL_LATITUDE_1
    walls.append(Wall(WALL_LONGITUDE_1, WALL_LATITUDE_1, Orientation.HORIZONTAL, WALL_LATITUDE_1_THICKNESS, WALL_HORIZONTAL_LENGTH_1))
    # WALL_LATITUDE_2
    walls.append(Wall(WALL_LONGITUDE_1+THIN_WALL_THICKNESS+LANE_SIZE, WALL_LATITUDE_2, Orientation.HORIZONTAL, WALL_LATITUDE_2_THICKNESS, WALL_HORIZONTAL_LENGTH_2))
    walls.append(Wall(WALL_LONGITUDE_3, WALL_LATITUDE_2, Orientation.HORIZONTAL, WALL_LATITUDE_2_THICKNESS, WALL_HORIZONTAL_LENGTH_3))
    walls.append(Wall(WALL_LONGITUDE_6-WALL_LONGITUDE_6_THICKNESS, WALL_LATITUDE_2, Orientation.HORIZONTAL, WALL_LATITUDE_2_THICKNESS, WALL_HORIZONTAL_LENGTH_3))
    walls.append(Wall(WALL_LONGITUDE_8, WALL_LATITUDE_2, Orientation.HORIZONTAL, WALL_LATITUDE_2_THICKNESS, WALL_HORIZONTAL_LENGTH_2))

    # WALL_LATITUDE_3
    #walls.append(Wall(WALL_LONGITUDE_1+THICK_WALL_THICKNESS+LANE_SIZE, WALL_LATITUDE_2, Orientation.HORIZONTAL, WALL_LATITUDE_2_THICKNESS, WALL_LONGITUDE_9-WALL_LONGITUDE_1+THIN_WALL_THICKNESS))

    return walls